services:
  # MySQL 설정
  mysql:
    image: mysql:latest
    container_name: my-mysql
    environment:
      MYSQL_ROOT_PASSWORD: qwer1234
      MYSQL_DATABASE: semi_project
      MYSQL_USER: suojae
      MYSQL_PASSWORD: qwer12345
    ports:
      - "3306:3306"
    networks:
      - backend
    volumes:
      - mysql_data:/var/lib/mysql

  # Redis 설정
  redis:
    image: redis:latest
    container_name: my-redis
    ports:
      - "3000:3000"
    environment:
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_USER: suojae
      DATABASE_PASSWORD: qwer1234
      DATABASE_NAME: semi_project
      REDIS_HOST: redis
      REDIS_PORT: 6379

    depends_on:
      - mysql

# 네트워크 설정
networks:
  backend:
    driver: bridge

# 볼륨 설정
volumes:
  mysql_data:
  redis_data: